In [ ]:
# pip install keras
# pip install tensorflow
#!pip install gradio

In [2]:
import numpy as np
import pandas as pd
import keras

In [3]:
from  keras.datasets import mnist

In [4]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [5]:
X_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

## Data Pre-processing

In [6]:
X_train.shape

(60000, 28, 28)

In [7]:
y_train.shape

(60000,)

In [8]:
y_test.shape

(10000,)

Converting data to NHWC format

In [9]:
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)

input_shape = (28, 28, 1)

X_train.shape

(60000, 28, 28, 1)

In [10]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [11]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

Conversion of class vector to matrix of binary classes

In [12]:
num_classes = 10
num_classes

10

In [13]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

y_test.shape

(10000, 10)

In [14]:
y_train.shape

(60000, 10)

In [15]:
# converting X type to float

X_train = X_train.astype(np.float32)
X_test = X_test.astype(np.float32)

# scaling X to range between (0, 1)

X_train /= 255
X_test /= 255

X_train

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

## Creating Model

In [16]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dropout
from keras.layers import Dense
from keras.layers import Flatten

In [17]:
model = Sequential()
model.add(Conv2D(filters=32, kernel_size=[5, 5], padding='same', activation='relu', name='conv1', input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2), strides=2, name='pool1'))
model.add(Conv2D(filters=64, kernel_size=[5, 5], padding='same',activation='relu',name='conv2'))
model.add(MaxPooling2D(pool_size=(2, 2), strides=2, name='pool2'))
model.add(Flatten())
model.add(Dense(1024, activation='relu', name='dense1'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

In [20]:
import tensorflow as tf

In [21]:
model.compile(loss=keras.losses.categorical_crossentropy,optimizer=tf.compat.v1.train.AdamOptimizer(),metrics=['accuracy'])

## Train Model

In [22]:
X_train.shape,X_test.shape, y_train.shape,y_test.shape,


((60000, 28, 28, 1), (10000, 28, 28, 1), (60000, 10), (10000, 10))

In [23]:
y_test

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [24]:
model.fit(X_train, y_train, batch_size=128, epochs=10, verbose=1, validation_data=(X_test, y_test))

Epoch 1/10
469/469 [==============================] - 225s 477ms/step - loss: 0.1589 - accuracy: 0.9508 - val_loss: 0.0355 - val_accuracy: 0.9884
Epoch 2/10
469/469 [==============================] - 221s 471ms/step - loss: 0.0475 - accuracy: 0.9855 - val_loss: 0.0270 - val_accuracy: 0.9914
Epoch 3/10
469/469 [==============================] - 223s 475ms/step - loss: 0.0316 - accuracy: 0.9902 - val_loss: 0.0248 - val_accuracy: 0.9916
Epoch 4/10
469/469 [==============================] - 223s 475ms/step - loss: 0.0228 - accuracy: 0.9927 - val_loss: 0.0227 - val_accuracy: 0.9914
Epoch 5/10
469/469 [==============================] - 218s 466ms/step - loss: 0.0195 - accuracy: 0.9938 - val_loss: 0.0206 - val_accuracy: 0.9938
Epoch 6/10
469/469 [==============================] - 222s 474ms/step - loss: 0.0153 - accuracy: 0.9948 - val_loss: 0.0296 - val_accuracy: 0.9913
Epoch 7/10
469/469 [==============================] - 222s 475ms/step - loss: 0.0135 - accuracy: 0.9956 - val_loss: 0.0200 -

In [25]:
model.save('mnist')

## Evalute Model

In [26]:
scores = model.evaluate(X_test, y_test, verbose=0)
scores

[0.023996908217668533, 0.9929999709129333]

In [27]:
print('Test loss:', scores[0])
print('Test Accuracy:', scores[1])

Test loss: 0.023996908217668533
Test Accuracy: 0.9929999709129333


## Creating GUI for Digit Recognizer

In [31]:
# !pip install gradio

In [30]:
import gradio as gr

In [32]:
def classify(input):
    prediction = model.predict(input.reshape(1, 28, 28)).tolist()[0]
    return {str(i): prediction[i] for i in range(10)}

label = gr.outputs.Label(num_top_classes=3)
interface = gr.Interface(fn=classify, inputs="sketchpad", outputs=label,
live=True)
interface.launch(share=True)

<ipython-input-32-c5390cf92d12>:5: GradioDeprecationWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
  label = gr.outputs.Label(num_top_classes=3)
<ipython-input-32-c5390cf92d12>:5: GradioUnusedKwargWarning: You have unused kwarg parameters in Label, please remove them: {'type': 'auto'}
  label = gr.outputs.Label(num_top_classes=3)


Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://e9813bf612f8330326.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
